name: Call API on Master Branch Update

on:
  push:
    branches:
      - master

jobs:
  call_api:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Call API
        run: |
          curl -X GET https://api.snippets.it.com/api/pull
